/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uas_pbd_yuga_057;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author WIN11
 */
public class AccountProfileDialog extends javax.swing.JDialog {

    /**
     * Creates new form AccountProfileDialog
     */
    public AccountProfileDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null); // // memposisikan di tengah layar
        setIconImage(new ImageIcon(getClass().getResource("/uas_pbd_yuga_057/images/logo.jpeg")).getImage()); // ubah ikon program
        loadAccountProfile(); // panggil fungsi untuk load account profile
    }
    
    Connection con; // Deklarasi variabel untuk koneksi database
    PreparedStatement pst; // Deklarasi variabel untuk statement SQL
    ResultSet rs; // Deklarasi variabel untuk hasil kueri SQL
    
    private boolean isPasswordVisible = false;

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        lblWelcome = new javax.swing.JLabel();
        Username2 = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        txtPass = new javax.swing.JPasswordField();
        Username = new javax.swing.JLabel();
        btnChange = new javax.swing.JButton();
        btnShowPass = new javax.swing.JButton();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitle.setBackground(new java.awt.Color(255, 255, 255));
        lblTitle.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblTitle.setText("Profile Account");
        lblTitle.setOpaque(true);
        jPanel1.add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, -1, -1));

        lblWelcome.setBackground(new java.awt.Color(255, 255, 255));
        lblWelcome.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblWelcome.setText("Change Your Username and Password");
        lblWelcome.setOpaque(true);
        jPanel1.add(lblWelcome, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, -1, -1));

        Username2.setBackground(new java.awt.Color(255, 255, 255));
        Username2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Username2.setText("Username : ");
        Username2.setOpaque(true);
        jPanel1.add(Username2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, -1, -1));
        jPanel1.add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, 330, 30));
        jPanel1.add(txtPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 210, 330, -1));

        Username.setBackground(new java.awt.Color(255, 255, 255));
        Username.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Username.setText("Password : ");
        Username.setOpaque(true);
        jPanel1.add(Username, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, -1, -1));

        btnChange.setText("Change");
        btnChange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangeActionPerformed(evt);
            }
        });
        jPanel1.add(btnChange, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 250, -1, -1));

        btnShowPass.setText("Show Password");
        btnShowPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowPassActionPerformed(evt);
            }
        });
        jPanel1.add(btnShowPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 250, -1, -1));

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uas_pbd_yuga_057/images/gambar-4.jpg"))); // NOI18N
        jPanel1.add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 320));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnChangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangeActionPerformed
        try {
            int id = UserSession.userId; // ambil data user id di class UserSession
            // TODO add your handling code here:
            String sql = "UPDATE akun SET username=?, password=? WHERE id=?";
            con = Config.configDB();
            pst = con.prepareStatement(sql);
            pst.setString(1, txtUsername.getText());
            pst.setString(2, txtPass.getText());
            pst.setInt(3, id);
            
            int rowsAffected = pst.executeUpdate();
            if(rowsAffected > 0){
                JOptionPane.showMessageDialog(null, "berhasil ubah akun"); // pesan notifikasi
                
            }else{
                JOptionPane.showMessageDialog(null, "gagal ubah akun"); // pesan notifikasi
            }
        } catch (Exception ex) {
            Logger.getLogger(AccountProfileDialog.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnChangeActionPerformed

    private void btnShowPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowPassActionPerformed
        // Mengecek apakah password saat ini terlihat (isPasswordVisible adalah true)
    if (isPasswordVisible) {
        // Mengatur ulang karakter echo untuk menyembunyikan teks password
        // '*' adalah karakter bullet default yang digunakan untuk menyembunyikan password
        // Anda bisa mengganti '*' dengan karakter lain yang diinginkan untuk menyembunyikan password
        txtPass.setEchoChar('*');
        
        // Mengubah teks tombol menjadi "Show Password" untuk memberikan indikasi bahwa klik berikutnya akan menampilkan password
        btnShowPass.setText("Show Password");
    } else {
        // Menampilkan teks password sebagai teks biasa dengan mengatur karakter echo menjadi null (0)
        // Mengatur karakter echo ke (char) 0 akan menampilkan teks asli tanpa perubahan
        txtPass.setEchoChar((char) 0);
        
        // Mengubah teks tombol menjadi "Hide Password" untuk memberikan indikasi bahwa klik berikutnya akan menyembunyikan password
        btnShowPass.setText("Hide Password");
    }
    
    // Membalik nilai dari isPasswordVisible; 
    // jika sebelumnya true maka menjadi false, dan sebaliknya
    // Ini akan digunakan pada klik tombol berikutnya untuk menentukan apakah password harus ditampilkan atau disembunyikan
    isPasswordVisible = !isPasswordVisible;
    }//GEN-LAST:event_btnShowPassActionPerformed

    private void loadAccountProfile(){
        try {
            // Mengambil ID produk yang dipilih dari JComboBox dan menyimpannya dalam variabel pid
            int pid = UserSession.userId;

        // Membuat pernyataan SQL untuk memilih data produk berdasarkan ID dari tabel 'product'
        con = (Connection) Config.configDB();
        pst = con.prepareStatement("SELECT * FROM AKUN WHERE id=?");
        pst.setInt(1, pid); // Mengatur nilai parameter pertama (?) dengan nilai dari variabel pid
        rs = pst.executeQuery(); // Mengeksekusi pernyataan SQL dan mendapatkan hasilnya

        // Memeriksa apakah hasil kueri mengandung baris data
        if (rs.next()) {

            // Jika ada data, mengatur nilai JTextField txtName, txtPrice, dan txtQty dengan nilai dari hasil kueri
            txtUsername.setText(rs.getString(2)); // Mengatur nilai txtName dengan nilai dari kolom kedua (nama produk)
            txtPass.setText(rs.getString(3)); // Mengatur nilai txtSize dengan nilai dari kolom ketiga (ukuran produk)
        }
        } catch (Exception e) {
        
    }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AccountProfileDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AccountProfileDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AccountProfileDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AccountProfileDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AccountProfileDialog dialog = new AccountProfileDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JLabel Username;
    private javax.swing.JLabel Username2;
    private javax.swing.JButton btnChange;
    private javax.swing.JButton btnShowPass;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblWelcome;
    private javax.swing.JPasswordField txtPass;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
