/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uas_pbd_yuga_057;

import java.sql.Connection;
import java.sql.PreparedStatement;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author WIN11
 */
public class RegisterForm extends javax.swing.JFrame {

    /**
     * Creates new form RegisterForm
     */
    public RegisterForm() {
        initComponents();
        setLocationRelativeTo(null);
        setIconImage(new ImageIcon(getClass().getResource("/uas_pbd_yuga_057/images/logo.jpeg")).getImage());
    }
    
    private boolean isPasswordVisible = false;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Username1 = new javax.swing.JLabel();
        Username = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        txtPass = new javax.swing.JPasswordField();
        btnCreateAccount = new javax.swing.JButton();
        btnShowPass = new javax.swing.JButton();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("RAVAZKA Shop");

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("Register");
        jLabel2.setOpaque(true);
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, -1, -1));

        Username1.setBackground(new java.awt.Color(255, 255, 255));
        Username1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Username1.setText("Username : ");
        Username1.setOpaque(true);
        jPanel1.add(Username1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        Username.setBackground(new java.awt.Color(255, 255, 255));
        Username.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Username.setText("Password : ");
        Username.setOpaque(true);
        jPanel1.add(Username, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));
        jPanel1.add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, 330, 30));
        jPanel1.add(txtPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 170, 330, -1));

        btnCreateAccount.setBackground(new java.awt.Color(204, 204, 204));
        btnCreateAccount.setText("CREATE ACCOUNT");
        btnCreateAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateAccountActionPerformed(evt);
            }
        });
        jPanel1.add(btnCreateAccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 220, -1, -1));

        btnShowPass.setText("Show Password");
        btnShowPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowPassActionPerformed(evt);
            }
        });
        jPanel1.add(btnShowPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 220, -1, -1));

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uas_pbd_yuga_057/images/gambarToko-2.jpg"))); // NOI18N
        jPanel1.add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 491));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateAccountActionPerformed
        // TODO add your handling code here:
        try {
            // Mendefinisikan query SQL untuk memasukkan data ke tabel akun dengan kolom username dan password
            String sql = "INSERT INTO akun (username, password) VALUES (?, ?)";

            // Membuat koneksi ke database menggunakan konfigurasi dari Config.configDB()
            java.sql.Connection con = (Connection) Config.configDB();

            // Membuat PreparedStatement untuk eksekusi query SQL yang telah didefinisikan
            PreparedStatement statement = con.prepareStatement(sql);

            // Mengatur nilai parameter pertama (?) pada query dengan teks dari txtUsername
            statement.setString(1, txtUsername.getText());

            // Mengatur nilai parameter kedua (?) pada query dengan teks dari txtPass
            statement.setString(2, txtPass.getText());

            // Mengeksekusi update (insert) dan menyimpan jumlah baris yang terpengaruh
            int rowsAffected = statement.executeUpdate();

            // Memeriksa apakah ada baris yang terpengaruh (berarti insert berhasil)
            if (rowsAffected > 0) {
                // Menampilkan pesan bahwa pembuatan akun berhasil
                JOptionPane.showMessageDialog(null, "berhasil buat akun");

                // Menyembunyikan frame registrasi saat ini
                this.setVisible(false);

                // Menampilkan frame LoginForm
                new LoginForm().setVisible(true);
            } else {
                // Menampilkan pesan bahwa pembuatan akun gagal
                JOptionPane.showMessageDialog(null, "gagal buat akun");
            }
        } catch (Exception e) {
            // Menampilkan pesan kesalahan jika terjadi exception
            JOptionPane.showMessageDialog(this, e.getMessage());
        }

    }//GEN-LAST:event_btnCreateAccountActionPerformed

    private void btnShowPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowPassActionPerformed
        // Mengecek apakah password saat ini terlihat (isPasswordVisible adalah true)
        if (isPasswordVisible) {
            // Mengatur ulang karakter echo untuk menyembunyikan teks password
            // '*' adalah karakter bullet default yang digunakan untuk menyembunyikan password
            // Anda bisa mengganti '*' dengan karakter lain yang diinginkan untuk menyembunyikan password
            txtPass.setEchoChar('*');

            // Mengubah teks tombol menjadi "Show Password" untuk memberikan indikasi bahwa klik berikutnya akan menampilkan password
            btnShowPass.setText("Show Password");
        } else {
            // Menampilkan teks password sebagai teks biasa dengan mengatur karakter echo menjadi null (0)
            // Mengatur karakter echo ke (char) 0 akan menampilkan teks asli tanpa perubahan
            txtPass.setEchoChar((char) 0);

            // Mengubah teks tombol menjadi "Hide Password" untuk memberikan indikasi bahwa klik berikutnya akan menyembunyikan password
            btnShowPass.setText("Hide Password");
        }

        // Membalik nilai dari isPasswordVisible;
        // jika sebelumnya true maka menjadi false, dan sebaliknya
        // Ini akan digunakan pada klik tombol berikutnya untuk menentukan apakah password harus ditampilkan atau disembunyikan
        isPasswordVisible = !isPasswordVisible;
    }//GEN-LAST:event_btnShowPassActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JLabel Username;
    private javax.swing.JLabel Username1;
    private javax.swing.JButton btnCreateAccount;
    private javax.swing.JButton btnShowPass;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField txtPass;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
