/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uas_prak_pbd_yuga_057;

import java.io.FileInputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author WIN11
 */
public class TopUpDialog extends javax.swing.JDialog {

    /**
     * Creates new form TopUpDialog
     */
    public TopUpDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null); // Tambahkan ini untuk menempatkan frame di tengah
    }
    
    Connection con; // Deklarasi variabel untuk koneksi database
    PreparedStatement pst; // Deklarasi variabel untuk statement SQL
    ResultSet rs; // Deklarasi variabel untuk hasil kueri SQL
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        Title1 = new javax.swing.JLabel();
        Welcome2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtTopUp = new javax.swing.JTextField();
        btnTopUp = new javax.swing.JButton();
        Background1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Title1.setBackground(new java.awt.Color(255, 255, 255));
        Title1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Title1.setText("Form Top Up Pembayaran");
        Title1.setOpaque(true);
        jPanel2.add(Title1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, -1, -1));

        Welcome2.setBackground(new java.awt.Color(255, 255, 255));
        Welcome2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Welcome2.setText("Pilih Produk yang akan dibeli");
        Welcome2.setOpaque(true);
        jPanel2.add(Welcome2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Amount of money");
        jLabel9.setOpaque(true);
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, -1, 20));

        txtTopUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTopUpActionPerformed(evt);
            }
        });
        jPanel2.add(txtTopUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 190, 230, -1));

        btnTopUp.setText("Top Up");
        btnTopUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTopUpActionPerformed(evt);
            }
        });
        jPanel2.add(btnTopUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 320, 180, -1));

        Background1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uas_prak_pbd_yuga_057/images/gambarToko-1.jpg"))); // NOI18N
        jPanel2.add(Background1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, 380));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTopUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTopUpActionPerformed
        // TODO add your handling code here:
        try {
            con = (Connection) Config.configDB();
    int moneyTopUp = Integer.parseInt(txtTopUp.getText()); // Mengambil teks dari JTextField txtName dan menyimpannya dalam variabel pname
    int userId = UserSession.userId;
    
        PreparedStatement pstAccountMoney = con.prepareStatement("SELECT money FROM akun WHERE id=?");
        pstAccountMoney.setInt(1, userId);
        ResultSet rsAccountMoney = pstAccountMoney.executeQuery();
        
        if (!rsAccountMoney.next()) {
            JOptionPane.showMessageDialog(this, "Account tidak ditemukan");
            return;
        }
        
        int moneyAccount = rsAccountMoney.getInt("money");
        int sumMoney = moneyAccount + moneyTopUp;
    
    pst = con.prepareStatement("UPDATE akun SET money=? WHERE id=?"); // Membuat pernyataan SQL untuk memasukkan data ke tabel 'product'
    pst.setInt(1, sumMoney); // Mengatur nilai parameter pertama (?) dengan nilai dari variabel pname
    pst.setInt(2, userId);

    int k = pst.executeUpdate(); // Mengeksekusi pernyataan SQL untuk memasukkan data ke dalam tabel dan mendapatkan jumlah baris yang terpengaruh

    if(k == 1){
        JOptionPane.showMessageDialog(this, "Top Up Successfully"); // Menampilkan pesan dialog jika data berhasil dimasukkan
        txtTopUp.setText(""); // Mengosongkan JTextField txtName
    }else{
        JOptionPane.showMessageDialog(this, "Top Up Failed"); // Menampilkan pesan dialog jika data gagal disimpan
    }
} catch (SQLException ex) {
    Logger.getLogger(TopUpDialog.class.getName()).log(Level.SEVERE, null, ex); // Menangani kesalahan jika terjadi kesalahan dalam eksekusi kueri SQL
}       catch (Exception ex) {
            Logger.getLogger(TopUpDialog.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnTopUpActionPerformed

    private void txtTopUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTopUpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTopUpActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TopUpDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TopUpDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TopUpDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TopUpDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TopUpDialog dialog = new TopUpDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background1;
    private javax.swing.JLabel Title1;
    private javax.swing.JLabel Welcome2;
    private javax.swing.JButton btnTopUp;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtTopUp;
    // End of variables declaration//GEN-END:variables
}
